In [9]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

dtype = {'Oil (BBLS)': float, 'Water (BBLS)': float, 'Gas (MCF)': float, 'TP': float, 'CP': float}
df = pd.read_json('data.json')
df = df.fillna('')
df.Date = pd.to_datetime(df.Date)
df = df.sort_values(['Date', 'Well Name'], ascending = [False , True])

In [3]:
# Append daily production data to data.csv

# production_date_counter = input('Production from how many days ago? ')
# importFile = 'custom-report-cml_' + str(datetime.date.today() - pd.to_timedelta(production_date_counter +'day')) + '_9-00-03.csv'

# Get list of days that need production imported. Prevents the need for manual input 
end = datetime.today().date() # Gets today's date
start = df.iloc[0]['Date'].date() # Gets the most recent date from the dataframe
numdays = (end-start).days # Calculates the number of days between the above two dates
date_list = [end - timedelta(days=x) for x in range(numdays)]


#  Loop through dates that need production imported and try the different file name possibilities based on when the server sends the emails
for i in range(numdays-1):
    try:
        importFile = 'custom-report-cml_' + str(date_list[i]) + '_9-00-03.csv'
        dfImport = pd.read_csv(importFile, dtype = dtype, thousands=',')
    except:
        try:
            importFile = 'custom-report-cml_' + str(date_list[i]) + '_9-00-04.csv'
            dfImport = pd.read_csv(importFile, dtype = dtype, thousands=',')
        except:
            try:
                importFile = 'custom-report-cml_' + str(date_list[i]) + '_9-00-02.csv'
                dfImport = pd.read_csv(importFile, dtype = dtype, thousands=',')
            except:
                print('The latest production has not been imported from iWell yet.')
                break
    dfImport = dfImport.fillna('')
    dfImport.Date = pd.to_datetime(dfImport.Date)

    df = pd.concat([df,dfImport]).drop_duplicates()

df = df.sort_values(['Date', 'Well Name'], ascending = [False , True])

# Save to original data file
df.to_json('data.json')

In [4]:
# gas_col = df_query['Gas (MCF)']
# oil_col = df_query['Oil (BBLS)']

# df_query['GOR'] = gas_col/oil_col.replace(0,np.nan)*1000
# df_query['GOR'] = df_query['GOR'].astype(float)
# df_query['GOR'] = df_query['GOR'].round(decimals = 0)

# df_query.head()

In [5]:
# df3 = pd.read_excel('.\OneDrive - CML Exploration\CML\South Texas Prod Tracker.xlsm', index_col=[0])

import ipywidgets as widgets
from IPython.display import display, HTML
from ipywidgets import interact, Dropdown, interact_manual

import matplotlib.pyplot as plt
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
%matplotlib inline

datevar = "Today's date is: " + datetime.strftime(date_list[0], '%m-%d-%Y')

display(HTML(f'<h1><center>South Texas Production Dashboard</center></h1>'))
display(HTML(f'<h4><center>{datevar}</center></h4>'))

# Import from Quandl WTI crude oil price data
url = "https://www.quandl.com/api/v3/datasets/CHRIS/CME_CL1.csv"
wticl1 = pd.read_csv(url, index_col=0, parse_dates=True)

# Calculate monthly oil price
def oil_revenue(price, bopd):
    return round(price*.75*.954*bopd,2)

# Create wellname and date widgets to sort dataframe
well_list = df['Well Name'].unique().tolist()

wellnameW = widgets.Dropdown(
    options=well_list,
    description='Well Name:',
)

dateW = widgets.IntSlider(
    value=30, max=2000, min=7,
    description='Days of Production:',
)

@interact_manual(wellname = wellnameW, date=dateW)
def main(wellname, date):
    df_query = df[
            (df['Well Name'] == wellname) & 
            (df['Date'] > datetime.now() - pd.to_timedelta(f'{date}day'))
          ]
    
    # Get cum for entire well life regardless of days !!selected. That way cum oil is always correct
    df_cum = df[df['Well Name'] == wellname]
    cumoil = int(df_cum["Oil (BBLS)"].sum())
    
    try:
        print(f'This well has produced {cumoil} BBLS of oil')
        # Params
        plt.rcParams['figure.figsize'] = [15, 10]
        well_outputs = ['Oil (BBLS)', 'Water (BBLS)', 'Gas (MCF)']
        output_colors = ['g','b','r']
        sum_oil = int(df_query['Oil (BBLS)'].sum())
        oil_price = wticl1.iloc[0].Last

        fig, axs= plt.subplots(3)
        # Make 3 subplots for oil, water, and gas
        for i in range(3):
            axs[i].plot(df_query['Date'].tolist(), df_query[well_outputs[i]], color = output_colors[i])
            axs[i].set_title(f'{wellname} {well_outputs[i]} Production')
            axs[i].grid()

        fig.tight_layout()   
        plt.show()
        
    except:
        print('There are not enough days of production to create this graph.')

interactive(children=(Dropdown(description='Well Name:', options=('Aaron #1', 'Aniken #1', 'Anna Louisa #1', '…

In [6]:
@interact_manual(wellname = wellnameW, date=dateW)
def production(wellname, date):
    df_query = df[
        (df['Well Name'] == wellname) & 
        (df['Date'] > datetime.now() - pd.to_timedelta(f'{date}day'))
        ]
    pd.options.display.max_columns = None
    display(HTML(df_query.to_html()))
    
    print(f'This well has produced {int(df_query["Oil (BBLS)"].sum())} BBLS of oil in the selected time period')

interactive(children=(Dropdown(description='Well Name:', options=('Aaron #1', 'Aniken #1', 'Anna Louisa #1', '…

In [11]:
from openpyxl import load_workbook
wb = load_workbook(filename = '../CML/South Texas Prod Tracker.xlsm')

pd.read_csv('wellinfo.csv')

,Well Name,C,SPM,DH SL,Ideal bfpd,EPT,Est bfpd,Pump Eff,Pump Depth,GFLAP,Pump Inc
0,Aaron #1,0.262,5.6,128,187.8016,128,187.8,0.6,6554,1160,0
1,Aniken #1,0.182,7.1,52,67.1944,9,11.6,0.0,5616,0,8
2,Anna Louisa #1,0.182,6.5,104,123.032,20,23.7,0.0,6525,184,30
3,Annpick #1,0.182,5.4,48,47.1744,45,44.2,0.0,6853,544,87
4,Barrier #1,0.182,5.9,95,102.011,92,98.8,0.4,6428,667,30
...,...,...,...,...,...,...,...,...,...,...,...
85,Trotter #1,0.182,6.4,78,90.8544,77,89.7,0.3,6212,856,51
86,Vermillion #1,0.182,5.8,106,111.8936,106,111.9,0.0,6509,423,0 - has liner
87,Verna #1,0.182,5.4,74,72.7272,67,65.8,0.0,6984,242,90
88,White Marlin #1,0.262,6,86,135.192,71,111.6,0.0,7260,2327,78
89,Whittington #1,0.182,5.5,114,114.114,108,108.1,0.0,6765,12,53